# Generated by Django 5.0.6 on 2024-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='default_nickname', max_length=20, verbose_name='nickname'),
            preserve_default=False,
        ),
    ]
